'use client';

import { useState } from 'react';
import { supabase } from '@/lib/supabase';
import { getLiffProfile } from '@/lib/liff';
import { isWithinWarehouseArea } from '@/lib/geolocation';

export default function QueueRegistrationForm() {
  const [formData, setFormData] = useState({
    driverName: '',
    phoneNumber: '',
    vehiclePlate: '',
    company: '',
    scheduledTime: '',
  });
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isCheckingLocation, setIsCheckingLocation] = useState(false);
  const [message, setMessage] = useState<{ type: 'success' | 'error' | 'warning'; text: string } | null>(null);
  const [currentLocation, setCurrentLocation] = useState<{ lat: number; lng: number } | null>(null);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setIsCheckingLocation(true);
    setMessage(null);

    try {
      // Check location first
      const locationCheck = await isWithinWarehouseArea();

      // Get and display current location for debugging
      const { getCurrentLocation } = await import('@/lib/geolocation');
      const location = await getCurrentLocation();
      setCurrentLocation({ lat: location.latitude, lng: location.longitude });

      setIsCheckingLocation(false);

      if (!locationCheck.isWithin) {
        setMessage({
          type: 'error',
          text: locationCheck.message,
        });
        setIsSubmitting(false);
        return;
      }

      // Show success message for location check
      setMessage({
        type: 'warning',
        text: locationCheck.message,
      });

      const profile = await getLiffProfile();

      const { data, error } = await supabase
        .from('queues')
        .insert([
          {
            driver_name: formData.driverName,
            phone_number: formData.phoneNumber,
            vehicle_plate: formData.vehiclePlate,
            company: formData.company,
            scheduled_time: formData.scheduledTime,
            line_user_id: profile?.userId || '',
            queue_number: '', // Will be auto-generated by trigger
            check_in_latitude: location.latitude,
            check_in_longitude: location.longitude,
          },
        ])
        .select();

      if (error) throw error;

      setMessage({
        type: 'success',
        text: `ลงทะเบียนสำเร็จ! หมายเลขคิวของคุณคือ ${data[0].queue_number}`,
      });

      // Reset form
      setFormData({
        driverName: '',
        phoneNumber: '',
        vehiclePlate: '',
        company: '',
        scheduledTime: '',
      });
    } catch (error) {
      console.error('Error:', error);
      setMessage({
        type: 'error',
        text: error instanceof Error ? error.message : 'เกิดข้อผิดพลาดในการลงทะเบียน กรุณาลองใหม่อีกครั้ง',
      });
    } finally {
      setIsSubmitting(false);
      setIsCheckingLocation(false);
    }
  };

  // Version number - auto-incremented on each deployment
  const buildVersion = process.env.NEXT_PUBLIC_APP_VERSION || Date.now().toString().slice(-8);

  return (
    <form onSubmit={handleSubmit} className="space-y-6 relative">
      {currentLocation && (
        <div className="p-4 rounded-lg bg-blue-50 text-blue-800 border border-blue-200">
          <div className="font-semibold mb-2">📍 พิกัด GPS ที่จับได้จากอุปกรณ์ของคุณ:</div>
          <div className="font-mono text-sm space-y-1">
            <div>Latitude: {currentLocation.lat.toFixed(7)}</div>
            <div>Longitude: {currentLocation.lng.toFixed(7)}</div>
          </div>
          <div className="mt-2 text-xs text-blue-600">
            * นี่คือพิกัดที่ GPS ของอุปกรณ์คุณจับได้ ใช้สำหรับปรับแต่งขอบเขตพื้นที่
          </div>
        </div>
      )}

      {message && (
        <div
          className={`p-4 rounded-lg ${
            message.type === 'success'
              ? 'bg-green-50 text-green-800 border border-green-200'
              : message.type === 'warning'
              ? 'bg-yellow-50 text-yellow-800 border border-yellow-200'
              : 'bg-red-50 text-red-800 border border-red-200'
          }`}
        >
          {message.text}
        </div>
      )}

      {isCheckingLocation && (
        <div className="p-4 rounded-lg bg-blue-50 text-blue-800 border border-blue-200 flex items-center gap-3">
          <svg className="animate-spin h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
          </svg>
          <span>กำลังตรวจสอบตำแหน่งของคุณ...</span>
        </div>
      )}

      <div>
        <label htmlFor="driverName" className="block text-sm font-medium text-gray-700 mb-2">
          ชื่อ-นามสกุล คนขับรถ <span className="text-red-500">*</span>
        </label>
        <input
          type="text"
          id="driverName"
          name="driverName"
          value={formData.driverName}
          onChange={handleChange}
          required
          className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-all"
          placeholder="กรอกชื่อ-นามสกุล"
        />
      </div>

      <div>
        <label htmlFor="phoneNumber" className="block text-sm font-medium text-gray-700 mb-2">
          เบอร์โทรศัพท์ <span className="text-red-500">*</span>
        </label>
        <input
          type="tel"
          id="phoneNumber"
          name="phoneNumber"
          value={formData.phoneNumber}
          onChange={handleChange}
          required
          className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-all"
          placeholder="08X-XXX-XXXX"
        />
      </div>

      <div>
        <label htmlFor="vehiclePlate" className="block text-sm font-medium text-gray-700 mb-2">
          ทะเบียนรถ <span className="text-red-500">*</span>
        </label>
        <input
          type="text"
          id="vehiclePlate"
          name="vehiclePlate"
          value={formData.vehiclePlate}
          onChange={handleChange}
          required
          className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-all"
          placeholder="กข-1234"
        />
      </div>

      <div>
        <label htmlFor="company" className="block text-sm font-medium text-gray-700 mb-2">
          บริษัท/หน่วยงาน <span className="text-red-500">*</span>
        </label>
        <input
          type="text"
          id="company"
          name="company"
          value={formData.company}
          onChange={handleChange}
          required
          className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-all"
          placeholder="กรอกชื่อบริษัท"
        />
      </div>

      <div>
        <label htmlFor="scheduledTime" className="block text-sm font-medium text-gray-700 mb-2">
          วันและเวลาที่ต้องการรับของ <span className="text-red-500">*</span>
        </label>
        <input
          type="datetime-local"
          id="scheduledTime"
          name="scheduledTime"
          value={formData.scheduledTime}
          onChange={handleChange}
          required
          className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-all"
        />
      </div>

      <button
        type="submit"
        disabled={isSubmitting}
        className={`w-full py-4 px-6 rounded-lg font-medium text-white transition-all ${
          isSubmitting
            ? 'bg-gray-400 cursor-not-allowed'
            : 'bg-gradient-to-r from-indigo-600 to-blue-600 hover:from-indigo-700 hover:to-blue-700 shadow-lg hover:shadow-xl'
        }`}
      >
        {isSubmitting ? (
          <span className="flex items-center justify-center">
            <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
            กำลังลงทะเบียน...
          </span>
        ) : (
          'ลงทะเบียนคิว'
        )}
      </button>

      {/* Version display */}
      <div className="text-xs text-gray-400 mt-4">
        v{buildVersion}
      </div>
    </form>
  );
}
